// export const LOAD_TRADES = 'LOAD_TRADES';
// export const UPDATE_TRADES = 'UPDATE_TRADES';
// export const CREATE_TRADES = 'CREATE_TRADES';

// export const LOAD_COMMODITIES = 'LOAD_COMMODITIES';
// export const LOAD_COUNTERPARTIES = 'LOAD_COUNTERPARTIES';
// export const LOAD_LOCATIONS = 'LOAD_LOCATIONS';

export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
